import {
  AllGraduates,
  Atuda,
  AtudaMilitary,
  AtudaStudies,
  Bagrut,
  BagrutServiceStudents,
  DegreeServiceStudents,
  FinalRemarks,
  MappingReference,
  NationalService,
  Overview,
  PreArmy,
  Released,
  ReleasedLost,
  ReleasedMilitary,
  ReleasedStudents,
  ReleasedTravelers,
  ReleasedWork,
  ReturnIntent,
  SocialNetwork,
  Soldiers,
  StudyingDuringService,
} from "./pages";

export const MAIN_PAGE = "Overview";

export const PAGES = {
  AllGraduates,
  Atuda,
  AtudaMilitary,
  AtudaStudies,
  Bagrut,
  BagrutServiceStudents,
  DegreeServiceStudents,
  FinalRemarks,
  MappingReference,
  NationalService,
  Overview,
  PreArmy,
  Released,
  ReleasedLost,
  ReleasedMilitary,
  ReleasedStudents,
  ReleasedTravelers,
  ReleasedWork,
  ReturnIntent,
  SocialNetwork,
  Soldiers,
  StudyingDuringService,
};
