import {
  AllGraduates,
  Atuda,
  AtudaMilitary,
  AtudaStudies,
  Bagrut,
  BagrutServiceStudents,
  DegreeServiceStudents,
  FinalRemarks,
  MappingReference,
  NationalService,
  Overview,
  PreArmy,
  Released,
  ReleasedLost,
  ReleasedMilitary,
  ReleasedStudents,
  ReleasedTravelers,
  ReleasedWork,
  ReturnIntent,
  SocialNetwork,
  Soldiers,
  StudyingDuringService,
} from "./pages";
import __Layout from "./Layout";

const PAGES = {
  AllGraduates,
  Atuda,
  AtudaMilitary,
  AtudaStudies,
  Bagrut,
  BagrutServiceStudents,
  DegreeServiceStudents,
  FinalRemarks,
  MappingReference,
  NationalService,
  Overview,
  PreArmy,
  Released,
  ReleasedLost,
  ReleasedMilitary,
  ReleasedStudents,
  ReleasedTravelers,
  ReleasedWork,
  ReturnIntent,
  SocialNetwork,
  Soldiers,
  StudyingDuringService,
};

export const pagesConfig = {
  mainPage: "Overview",
  Pages: PAGES,
  Layout: __Layout,
};
